# -*- coding: utf-8 -*-
"""businessanalsytproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHAQO41NcGeoG84AXVe4_AK8bWR0AyWA
"""

!pip install kaggle
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d computingvictor/transactions-fraud-datasets

!unzip transactions-fraud-datasets.zip

# prompt: load dataframes of  transactions-fraud-datasets.zip

import pandas as pd

# Assuming the unzipped files are in the current directory
# and the relevant file is 'transactions.csv' (replace if different)

try:
  df_transactions = pd.read_csv('transactions_data.csv')
  print("Transactions DataFrame loaded successfully.")
  print(df_transactions.head()) # Display the first few rows
except FileNotFoundError:
  print("Error: transactions.csv not found. Check the file name and location.")
except pd.errors.ParserError:
    print("Error: Could not parse transactions.csv. Check the file format.")
except Exception as e:
  print(f"An unexpected error occurred: {e}")

df_transactions.info()

#load mcc_codes from json and join on df_transactions

import json
import pandas as pd # Ensure pandas is imported

try:
  with open('mcc_codes.json', 'r') as json_file:
    mcc_codes = json.load(json_file)
    print("MCC codes loaded successfully.")
    # Create DataFrame with MCC codes as index and descriptions as a column
    df_mcc_codes = pd.DataFrame.from_dict(mcc_codes, orient='index', columns=['description'])
    print(df_mcc_codes.head()) # Display the first few rows
    # Reset the index and drop the old index
    df_mcc_codes = df_mcc_codes.reset_index().rename(columns={'index': 'mcc'})
except FileNotFoundError:
  print("Error: mcc_codes.json not found. Check the file name and location.")

#set dtype of column 1 to int64
df_mcc_codes['mcc'] = df_mcc_codes['mcc'].astype('int64')

df_merged = df_transactions.merge(df_mcc_codes, on="mcc", how="left")

df_merged.head()

# Data Cleaning

df_merged.drop_duplicates(inplace = True)

# if merchant_city == ONLINE, set merchant_state and zip to None
df_merged.loc[df_merged['merchant_city'] == 'ONLINE', ['merchant_state', 'zip']] = ["N/A", "N/A"]

# fill error with N/A
df_merged['errors'].fillna('N/A', inplace=True)
df_merged['zip'] = df_merged['zip'].fillna('N/A')
df_merged.isnull().sum()

# print all rows with naN zip column

df_merged[df_merged['zip'].isna()]

df_merged['amount'].head()
# remove dollar sign and convert amount to float
df_merged['amount'] = df_merged['amount'].str.replace('$', '').astype(float)

df_merged['timestamp'] = pd.to_datetime(df_merged['date'])

df_merged.drop('date', axis=1, inplace=True)

df_merged['day_of_week'] = df_merged['timestamp'].dt.day_name()
df_merged['hour'] = df_merged['timestamp'].dt.hour
df_merged['month'] = df_merged['timestamp'].dt.month

# for testing  plotting
df = df_merged.head(20000)

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(12, 5))
sns.histplot(df['hour'], bins=24, kde=True)
plt.title("Transaction Volume by Hour of the Day")
plt.xlabel("Hour")
plt.ylabel("Number of Transactions")
plt.show()

df['amount'] = df['amount'].astype(float)  # Convert to numeric if needed
top_clients = df.groupby('client_id')['amount'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10, 5))
sns.barplot(x=top_clients.index, y=top_clients.values)
plt.title("Top 10 Customers by Total Spend")
plt.xlabel("Client ID")
plt.ylabel("Total Amount Spent")
plt.show()

df['amount'] = df['amount'].astype(float)
sns.scatterplot(x='client_id', y='amount', data=df)
plt.title("Unusual Spending Patterns")
plt.show()

top_merchants = df['merchant_id'].value_counts().head(10)

plt.figure(figsize=(10, 5))
sns.barplot(x=top_merchants.index, y=top_merchants.values)
plt.title("Top 10 Merchants by Transaction Count")
plt.xlabel("Merchant ID")
plt.ylabel("Number of Transactions")
plt.show()

sns.countplot(x='use_chip', data=df)
plt.title("Chip vs. Non-Chip Transactions")
plt.show()

city_total_spending = df.groupby('merchant_city')['amount'].sum().sort_values(ascending=False).head(10)

# Plot the top 10 cities with highest spending
plt.figure(figsize=(12, 6))
sns.barplot(x=city_total_spending.index, y=city_total_spending.values, palette="Reds_r")
plt.xticks(rotation=45)
plt.title("Top 10 Merchant Cities by Total Transaction Amount")
plt.xlabel("Merchant City")
plt.ylabel("Total Amount Spent ($)")
plt.show()

# Create a DataFrame with both total transactions and total amount spent
city_stats = df.groupby('merchant_city').agg(
    total_transactions=('merchant_city', 'count'),
    total_spent=('amount', 'sum')
).sort_values(by='total_spent', ascending=False).head(10)

plt.figure(figsize=(12, 6))
sns.barplot(x=city_stats.index, y=city_stats['total_spent'], palette="Blues_r")
plt.xticks(rotation=45)
plt.title("Top 10 Merchant Cities by Total Amount Spent")
plt.xlabel("Merchant City")
plt.ylabel("Total Amount Spent ($)")
plt.show()

df['date'] = pd.to_datetime(df['timestamp'])  # Convert to datetime
df = df.sort_values(by=['client_id', 'timestamp'])  # Sort by client & time

# Compute time difference between consecutive transactions for each client
df['time_diff'] = df.groupby('client_id')['timestamp'].diff().dt.total_seconds() / 3600  # Convert to hours

# Find anomalies where transactions occur in different cities within a short period
df['location_change'] = df['merchant_city'] != df.groupby('client_id')['merchant_city'].shift(1)

# Flag anomalies where a location change happens within 2 hours
df['suspicious_travel'] = (df['location_change']) & (df['time_diff'] < 2)

# Display suspicious cases
suspicious_customers = df[df['suspicious_travel']]
print(suspicious_customers[['client_id', 'merchant_city', 'timestamp', 'time_diff']])



df['amount'] = df['amount'].astype(float)  # Convert 'amount' to numeric

# Calculate each customer's average and standard deviation of spending
client_stats = df.groupby('client_id')['amount'].agg(['mean', 'std']).reset_index()
client_stats.columns = ['client_id', 'avg_spend', 'spending_std']

# Merge back to original data
df = df.merge(client_stats, on='client_id', how='left')

# Define an anomaly: transaction > (avg + 3 * std deviation)
df['is_anomaly'] = df['amount'] > (df['avg_spend'] + 3 * df['spending_std'])

# Show anomalies
anomalies = df[df['is_anomaly']]
print(anomalies[['client_id', 'amount', 'avg_spend', 'spending_std']])

#export df_merged into csv file
df_merged.to_csv('df_merged.csv', index=False)